-- Meridian per-service schemas (idempotent). PostGIS available for geo svc.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS rp_registry;
CREATE SCHEMA IF NOT EXISTS tin_graph;
CREATE SCHEMA IF NOT EXISTS ledger;
CREATE SCHEMA IF NOT EXISTS audit_evidence;
CREATE SCHEMA IF NOT EXISTS consent;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS geo;
CREATE SCHEMA IF NOT EXISTS search_indexer;
CREATE SCHEMA IF NOT EXISTS edge_policy;
CREATE SCHEMA IF NOT EXISTS admin_api;
CREATE SCHEMA IF NOT EXISTS onboarding;
CREATE SCHEMA IF NOT EXISTS einvoicing;
CREATE SCHEMA IF NOT EXISTS permify;
CREATE SCHEMA IF NOT EXISTS keycloak;
