#!/usr/bin/env bash
# pin-images.sh — resolve production image tags to registry digests and emit a
# digest env file for docker-compose.prod.yml (+ a values snippet for helm).
#
# Policy: docs/image-pinning.md. This script NEVER invents a digest: every
# value is resolved live from the registry. If a tag cannot be resolved, the
# line is written commented-out with an error note, and the exit code is 1.
#
# Usage:
#   scripts/pin-images.sh [-f infra/docker-compose.prod.yml] [-o .env.prod.digests]
#
# Tool resolution order: crane -> skopeo -> docker (first found wins).
# Registry auth: uses your existing docker config / crane keychain / skopeo
# authfile; for private registries log in first.
set -u

COMPOSE_FILE="infra/docker-compose.prod.yml"
OUT=".env.prod.digests"
while [ $# -gt 0 ]; do
  case "$1" in
    -f) COMPOSE_FILE="$2"; shift 2;;
    -o) OUT="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

if command -v crane >/dev/null 2>&1; then
  resolve() { crane digest "$1" 2>/dev/null; }
elif command -v skopeo >/dev/null 2>&1; then
  resolve() { skopeo inspect --format '{{.Digest}}' "docker://$1" 2>/dev/null; }
elif command -v docker >/dev/null 2>&1; then
  # docker has no remote digest subcommand pre-25; pull+inspect fallback.
  resolve() {
    docker pull -q "$1" >/dev/null 2>&1 || return 1
    docker inspect --format '{{index .RepoDigests 0}}' "$1" 2>/dev/null | sed -n 's/.*@\(sha256:.*\)/\1/p'
  }
else
  echo "pin-images: need one of crane, skopeo, docker on PATH" >&2
  exit 2
fi

# tag_to_var: stable env-var name for an image reference.
# Must stay in sync with the ${IMG_*} names in docker-compose.prod.yml.
tag_to_var() {
  case "$1" in
    docker.redpanda.com/redpandadata/redpanda:*) echo IMG_REDPANDA;;
    postgis/postgis:*)            echo IMG_POSTGIS;;
    postgres:*)                   echo IMG_POSTGRES;;
    redis:*)                      echo IMG_REDIS;;
    temporalio/auto-setup:*)      echo IMG_TEMPORAL_AUTO_SETUP;;
    temporalio/ui:*)              echo IMG_TEMPORAL_UI;;
    opensearchproject/opensearch:*) echo IMG_OPENSEARCH;;
    minio/minio:*)                echo IMG_MINIO;;
    minio/mc:*)                   echo IMG_MINIO_MC;;
    ghcr.io/tigerbeetle/tigerbeetle:*) echo IMG_TIGERBEETLE;;
    busybox:*)                    echo IMG_BUSYBOX;;
    quay.io/keycloak/keycloak:*)  echo IMG_KEYCLOAK;;
    ghcr.io/permify/permify:*)    echo IMG_PERMIFY;;
    prom/prometheus:*)            echo IMG_PROMETHEUS;;
    prom/alertmanager:*)          echo IMG_ALERTMANAGER;;
    grafana/grafana:*)            echo IMG_GRAFANA;;
    bitnami/etcd:*)               echo IMG_ETCD;;
    apache/apisix:*)              echo IMG_APISIX;;
    tabulario/iceberg-rest:*)     echo IMG_ICEBERG_REST;;
    trinodb/trino:*)              echo IMG_TRINO;;
    *) echo "";;
  esac
}

repo_of() { echo "${1%:*}"; }

rc=0
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by scripts/pin-images.sh on $(date -u +%FT%TZ)."
  echo "# Merge into .env.prod (compose reads IMG_* via \${IMG_*:-tag} defaults)."
  echo "# Every value below was resolved from a live registry; commented lines"
  echo "# failed resolution and MUST NOT be uncommented with invented digests."
} > "$tmp"

# unique images, file order (process substitution keeps $rc in this shell)
while read -r var tag; do
  digest="$(resolve "$tag")"
  if [ -n "$digest" ]; then
    echo "${var}=$(repo_of "$tag")@${digest}"
  else
    echo "# UNRESOLVED: could not resolve digest for ${tag} — do NOT guess" >&2
    echo "# ${var}=UNRESOLVED-tag-was-${tag}"
    rc=1
  fi
done < <(grep -oE '\$\{IMG_[A-Z_]+:-[^}]+\}' "$COMPOSE_FILE" | sed -E 's/^\$\{(IMG_[A-Z_]+):-(.+)\}$/\1 \2/' | awk '!seen[$1]++') >> "$tmp" 2>&1

mv "$tmp" "$OUT"
echo "pin-images: wrote $OUT"
exit "$rc"
